apiVersion: v1
kind: Service
metadata:
  name: clo835-service
spec:
  type: NodePort
  selector:
    app: clo835-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3030
      nodePort: 30300